spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/estoque_produtos?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=618312

spring.jpa.hibernate.ddl-auto=update
